name: vulkan
description: Vulkan 1.2 FFI bindings for Dart. Supports Linux and Windows.
version: 0.5.0+1
homepage: https://gitlab.com/ext/dart-vulkan

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  ffi: ^1.1.0
  pedantic: ^1.0.0
  test: ^1.19.0

