name: vulkan
description: Vulkan 1.2 FFI bindings for Dart. Supports Linux and Windows.
version: 0.1.1
author: root ext <root.ext@gmail.com>
homepage: https://gitlab.com/ext/dart-vulkan

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  
dev_dependencies:
  ffi_utils: ^0.1.0
  glfw: ^0.2.0  
  pedantic: ^1.0.0

